import xml.etree.ElementTree as ET
import os

def create_vehicle_types():
    """Create vehicle types with emergency vehicles"""
    network_dir = 'network'
    vtypes_file = os.path.join(network_dir, 'vtypes.add.xml')
    
    root = ET.Element('additional', xmlns__xsi="http://www.w3.org/2001/XMLSchema-instance",
                     xsi__noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd")
    
    car = ET.SubElement(root, 'vType')
    car.set('id', 'car')
    car.set('accel', '2.0')
    car.set('decel', '3.5')
    car.set('sigma', '0.3')
    car.set('tau', '1.0')
    car.set('length', '4.8')
    car.set('width', '1.8')
    car.set('height', '1.5')
    car.set('maxSpeed', '30')
    car.set('color', '0.7,0.7,0.7')
    car.set('vClass', 'passenger')
    car.set('guiShape', 'passenger')
    car.set('emissionClass', 'HBEFA3/PC_G_EU4')
    
    bike = ET.SubElement(root, 'vType')
    bike.set('id', 'bike')
    bike.set('accel', '1.0')
    bike.set('decel', '2.5')
    bike.set('sigma', '0.2')
    bike.set('tau', '1.2')
    bike.set('length', '1.8')
    bike.set('width', '0.6')
    bike.set('height', '1.7')
    bike.set('maxSpeed', '15')
    bike.set('color', '0,1,0')
    bike.set('vClass', 'bicycle')
    bike.set('guiShape', 'bicycle')
    bike.set('emissionClass', 'zero')
    
    ambulance = ET.SubElement(root, 'vType')
    ambulance.set('id', 'ambulance')
    ambulance.set('accel', '3.0')
    ambulance.set('decel', '5.0')
    ambulance.set('sigma', '0.1')
    ambulance.set('tau', '0.8')
    ambulance.set('length', '6.5')
    ambulance.set('width', '2.1')
    ambulance.set('height', '2.8')
    ambulance.set('maxSpeed', '40')
    ambulance.set('color', '1,0,0')
    ambulance.set('vClass', 'emergency')
    ambulance.set('guiShape', 'emergency')
    ambulance.set('emissionClass', 'HBEFA3/LDV_G_EU6')
    ambulance.set('speedFactor', '1.3')
    ambulance.set('speedDev', '0.1')
    ambulance.set('impatience', '1.0')
    ambulance.set('lcStrategic', '10.0')
    ambulance.set('lcCooperative', '1.0')
    ambulance.set('lcSpeedGain', '5.0')
    
    police = ET.SubElement(root, 'vType')
    police.set('id', 'police')
    police.set('accel', '3.5')
    police.set('decel', '6.0')
    police.set('sigma', '0.05')
    police.set('tau', '0.7')
    police.set('length', '5.2')
    police.set('width', '1.9')
    police.set('height', '1.6')
    police.set('maxSpeed', '45')
    police.set('color', '0.8,0,0')
    police.set('vClass', 'emergency')
    police.set('guiShape', 'police')
    police.set('emissionClass', 'HBEFA3/LDV_G_EU6')
    police.set('speedFactor', '1.4')
    police.set('speedDev', '0.05')
    police.set('impatience', '1.0')
    police.set('lcStrategic', '12.0')
    police.set('lcCooperative', '1.0')
    police.set('lcSpeedGain', '6.0')
    
    firetruck = ET.SubElement(root, 'vType')
    firetruck.set('id', 'firetruck')
    firetruck.set('accel', '1.8')
    firetruck.set('decel', '3.5')
    firetruck.set('sigma', '0.15')
    firetruck.set('tau', '0.9')
    firetruck.set('length', '10.5')
    firetruck.set('width', '2.8')
    firetruck.set('height', '4.0')
    firetruck.set('maxSpeed', '35')
    firetruck.set('color', '0.9,0.1,0.1')
    firetruck.set('vClass', 'emergency')
    firetruck.set('guiShape', 'firebrigade')
    firetruck.set('emissionClass', 'HBEFA3/HDV_G')
    firetruck.set('speedFactor', '1.1')
    firetruck.set('speedDev', '0.1')
    firetruck.set('impatience', '1.0')
    firetruck.set('lcStrategic', '8.0')
    firetruck.set('lcCooperative', '1.0')
    firetruck.set('lcSpeedGain', '3.0')
    
    motorcycle = ET.SubElement(root, 'vType')
    motorcycle.set('id', 'motorcycle')
    motorcycle.set('accel', '2.5')
    motorcycle.set('decel', '4.5')
    motorcycle.set('sigma', '0.25')
    motorcycle.set('tau', '0.9')
    motorcycle.set('length', '2.2')
    motorcycle.set('width', '0.8')
    motorcycle.set('height', '1.5')
    motorcycle.set('maxSpeed', '35')
    motorcycle.set('color', '0.2,0.2,0.2')
    motorcycle.set('vClass', 'motorcycle')
    motorcycle.set('guiShape', 'motorcycle')
    motorcycle.set('emissionClass', 'HBEFA3/LDV_G_EU6')
    
    tree = ET.ElementTree(root)
    tree.write(vtypes_file, encoding='utf-8', xml_declaration=True)
    
    print(f"Vehicle types created: {vtypes_file}")
    print("Emergency vehicles: Ambulance, Police, Fire truck")
    
    return vtypes_file
